# Generated by Django 3.1.7 on 2021-03-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keywords',
            new_name='Keyword',
        ),
        migrations.AddField(
            model_name='article',
            name='middleReadingTime',
            field=models.CharField(default='unknown', max_length=4096),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(max_length=4096),
        ),
    ]
